### ISSUE TITLE
"Create New Test Suite" does not work when project is in a WSL folder

### ISSUE THREAD

**Issue by pontus-ullgren-ica** [wso2/mi-vscode#401]
**Description:**

Running VS Code on Windows 11 with the WSL extension to have the projects in WSL Ubuntu.
Micro Integrator extension installed in WSL-Ubuntu target. 

When creating a new Test Suite nothing appears to happen when pressing the "Create" button.

Looking in the "Extension Host (Remote)" output I see the following

```
2024-09-18 15:44:04.879 [error] TypeError: The "path" argument must be of type string. Received undefined
	at Object.join (node:path:1175:7)
	at /home/user/.vscode-server/extensions/wso2.micro-integrator-1.1.0/dist/extension.js:7:3412728
	at new Promise (<anonymous>)
	at t.MiDiagramRpcManager.updateTestSuite (/home/user/.vscode-server/extensions/wso2.micro-integrator-1.1.0/dist/extension.js:7:3412272)
	at Object.handler (/home/user/.vscode-server/extensions/wso2.micro-integrator-1.1.0/dist/extension.js:7:3328106)
	at t.Messenger.processRequestMessage (/home/user/.vscode-server/extensions/wso2.micro-integrator-1.1.0/dist/extension.js:12:2953716)
	at t.Messenger.processMessage (/home/user/.vscode-server/extensions/wso2.micro-integrator-1.1.0/dist/extension.js:12:2951663)
	at i.value (/home/user/.vscode-server/extensions/wso2.micro-integrator-1.1.0/dist/extension.js:12:2951384)
	at n.B (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:737)
	at n.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:954)
	at w.$onMessage (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:146:19363)
	at y.S (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:151:5980)
	at y.Q (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:151:5746)
	at y.M (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:151:4778)
	at y.L (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:151:3830)
	at i.value (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:151:2297)
	at n.B (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:737)
	at n.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:954)
	at s.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:97:14453)
	at i.value (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:177:8655)
	at n.B (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:737)
	at n.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:954)
	at s.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:97:14453)
	at d.A (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:97:17612)
	at i.value (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:97:15970)
	at n.B (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:737)
	at n.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:954)
	at m.acceptChunk (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:97:12199)
	at i.value (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:97:11469)
	at n.B (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:737)
	at n.fire (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:83:954)
	at s.z (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:21458)
	at s.acceptFrame (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:21264)
	at i.n (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:19709)
	at /home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:16636
	at Socket.v (/home/user/.vscode-server/bin/ffe1edb8d0f72a1dacf41e9f71a671c26ed924b9/out/vs/workbench/api/node/extensionHostProcess.js:174:14266)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
``` 

**Steps to reproduce:**

1. Setup VS Code on Windows with the WSL extension.
2. Connect the local WSL - Ubuntu distro as a target
3. Install the Micro Integrator extension in the WSL target
4. Create a new Micro Integrator project.
5. Implement a simple API
6. Try to create a Test Suite

**Affected Versions:**

1.1.0

**OS, DB, other environment details and versions:**

* Windows 11 
* WSL running Ubuntu 22.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
