### ISSUE TITLE
Not having empty "username" and "password" tags for RabbitMQ message store causes an error

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#51]
**Description:**
When creating a RabbitMQ message store, if a username or a password is not explicitly provided, the default values for them won't be picked unless the below lines are also included in the message store
```
<parameter name="store.rabbitmq.username"/>
<parameter name="store.rabbitmq.password"/>
```
This would cause the below error:
> Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
        at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQStore.resolveVaultExpressions(RabbitMQStore.java:383)
        at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQStore.initConnectionFactory(RabbitMQStore.java:147)
        at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQStore.init(RabbitMQStore.java:110)
        at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:59)

This needs to be fixed so that even if the empty tags are not provided, the default values will still be fixed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
