### ISSUE TITLE
Diagram is not rendering in Ubuntu on WSL

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#56]
The api diagram is not rendering when using Ubuntu on WSL.

Here is the output from the console Dev Tools :

Visualizer.js:435354 Uncaught TypeError: Cannot read properties of undefined (reading 'substring')
at Visualizer.js:435354:36
at commitHookEffectListMount (Visualizer.js:315931:26)
at commitPassiveMountOnFiber (Visualizer.js:317712:11)
at commitPassiveMountEffects_complete (Visualizer.js:317672:9)
at commitPassiveMountEffects_begin (Visualizer.js:317659:7)
at commitPassiveMountEffects (Visualizer.js:317647:3)
at flushPassiveEffectsImpl (Visualizer.js:319820:3)
at flushPassiveEffects (Visualizer.js:319765:14)
at performSyncWorkOnRoot (Visualizer.js:318857:3)
at flushSyncCallbacks (Visualizer.js:304828:22)
(anonymous) @ Visualizer.js:435354
commitHookEffectListMount @ Visualizer.js:315931
commitPassiveMountOnFiber @ Visualizer.js:317712
commitPassiveMountEffects_complete @ Visualizer.js:317672
commitPassiveMountEffects_begin @ Visualizer.js:317659
commitPassiveMountEffects @ Visualizer.js:317647
flushPassiveEffectsImpl @ Visualizer.js:319820
flushPassiveEffects @ Visualizer.js:319765
performSyncWorkOnRoot @ Visualizer.js:318857
flushSyncCallbacks @ Visualizer.js:304828
commitRootImpl @ Visualizer.js:319740
commitRoot @ Visualizer.js:319463
finishConcurrentRender @ Visualizer.js:318762
performConcurrentWorkOnRoot @ Visualizer.js:318590
workLoop @ Visualizer.js:373543
flushWork @ Visualizer.js:373516
performWorkUntilDeadline @ Visualizer.js:373810

Visualizer.js:311473 The above error occurred in the component:
at HierachicalPath (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:435334:111)
at NavButtonGroup (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:435438:111)
at div
at https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:3051:66
at NavigationBar
at div
at https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:3051:66
at MainPanel (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:434625:111)
at https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:435211:82
at ErrorBoundary (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:322758:5)
at ErrorBoundary (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:377407:176)
at Visualizer (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:435183:23)
at webpack_modules.../../../common/temp/node_modules/.pnpm/@[tanstack+react-query@4.0.10_biqbaboplfbrettd7655fr4n2y](mailto:tanstack+react-query@4.0.10_biqbaboplfbrettd7655fr4n2y)/node_modules/@tanstack/react-query/build/umd/index.production.js.t.QueryClientProvider (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:20794:39693)
at VisualizerContextProvider (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/wso2.micro-integrator-0.9.24062409/resources/jslibs/Visualizer.js:434422:38)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ Visualizer.js:311473
callback @ Visualizer.js:311536
callCallback @ Visualizer.js:306709
commitUpdateQueue @ Visualizer.js:306730
commitLayoutEffectOnFiber @ Visualizer.js:316145
commitLayoutMountEffects_complete @ Visualizer.js:317469
commitLayoutEffects_begin @ Visualizer.js:317455
commitLayoutEffects @ Visualizer.js:317393
commitRootImpl @ Visualizer.js:319604
commitRoot @ Visualizer.js:319463
performSyncWorkOnRoot @ Visualizer.js:318898
flushSyncCallbacks @ Visualizer.js:304828
commitRootImpl @ Visualizer.js:319740
commitRoot @ Visualizer.js:319463
finishConcurrentRender @ Visualizer.js:318762
performConcurrentWorkOnRoot @ Visualizer.js:318590
workLoop @ Visualizer.js:373543
flushWork @ Visualizer.js:373516
performWorkUntilDeadline @ Visualizer.js:373810

Visualizer.js:19192 Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
at PathFindingLinkFactory.calculateMatrixDimensions (Visualizer.js:19192:81)
at PathFindingLinkFactory.calculateCanvasMatrix (Visualizer.js:19304:105)
at PathFindingLinkFactory.getCanvasMatrix (Visualizer.js:19299:18)
at PathFindingLinkFactory.calculateRoutingMatrix (Visualizer.js:19334:41)
at Visualizer.js:19265:26
at Visualizer.js:258243:43

**Comment by thuva9872** [comment]
Possible Cause:
https://github.com/wso2-enterprise/vscode-extensions/blob/69f25babe26199382ec299ebd824551f994c4390/workspaces/mi/mi-visualizer/src/components/NavigationBar/HierachicalPath.tsx#L44

Here, since we're using Windows as the underlying platform with Ubuntu on top through WSL, it may still identify Windows as the platform because WSL doesn't isolate the system like a virtual machine does.
